# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/xdma_cmd_ram/xdma_cmd_ram.xci
# IP: The module: 'xdma_cmd_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/xdma_cmd_ram/xdma_cmd_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_cmd_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/xdma_cmd_ram/xdma_cmd_ram.xci
# IP: The module: 'xdma_cmd_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/xdma_cmd_ram/xdma_cmd_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_cmd_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
