# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath D:/modeltech64_2019.2/win64
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/wx/hdmi_movie/hdmi_movie.cache/wt [current_project]
set_property parent.project_path E:/wx/hdmi_movie/hdmi_movie.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/wx/hdmi_movie/hdmi_movie.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet E:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/shift_ram_sobel/shift_ram_sobel.xci
set_property used_in_implementation false [get_files -all e:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/shift_ram_sobel/shift_ram_sobel_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

set cached_ip [config_ip_cache -export -no_bom  -dir E:/wx/hdmi_movie/hdmi_movie.runs/shift_ram_sobel_synth_1 -new_name shift_ram_sobel -ip [get_ips shift_ram_sobel]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top shift_ram_sobel -part xc7a35tfgg484-2 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix shift_ram_sobel_ shift_ram_sobel.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ shift_ram_sobel_stub.v
 lappend ipCachedFiles shift_ram_sobel_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ shift_ram_sobel_stub.vhdl
 lappend ipCachedFiles shift_ram_sobel_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ shift_ram_sobel_sim_netlist.v
 lappend ipCachedFiles shift_ram_sobel_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ shift_ram_sobel_sim_netlist.vhdl
 lappend ipCachedFiles shift_ram_sobel_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp shift_ram_sobel.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips shift_ram_sobel]
}

rename_ref -prefix_all shift_ram_sobel_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef shift_ram_sobel.dcp
create_report "shift_ram_sobel_synth_1_synth_report_utilization_0" "report_utilization -file shift_ram_sobel_utilization_synth.rpt -pb shift_ram_sobel_utilization_synth.pb"

if { [catch {
  write_verilog -force -mode synth_stub E:/wx/hdmi_movie/hdmi_movie.runs/shift_ram_sobel_synth_1/shift_ram_sobel_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub E:/wx/hdmi_movie/hdmi_movie.runs/shift_ram_sobel_synth_1/shift_ram_sobel_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim E:/wx/hdmi_movie/hdmi_movie.runs/shift_ram_sobel_synth_1/shift_ram_sobel_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim E:/wx/hdmi_movie/hdmi_movie.runs/shift_ram_sobel_synth_1/shift_ram_sobel_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


}; # end if cached_ip 

add_files E:/wx/hdmi_movie/hdmi_movie.runs/shift_ram_sobel_synth_1/shift_ram_sobel_stub.v -of_objects [get_files E:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/shift_ram_sobel/shift_ram_sobel.xci]

add_files E:/wx/hdmi_movie/hdmi_movie.runs/shift_ram_sobel_synth_1/shift_ram_sobel_stub.vhdl -of_objects [get_files E:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/shift_ram_sobel/shift_ram_sobel.xci]

add_files E:/wx/hdmi_movie/hdmi_movie.runs/shift_ram_sobel_synth_1/shift_ram_sobel_sim_netlist.v -of_objects [get_files E:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/shift_ram_sobel/shift_ram_sobel.xci]

add_files E:/wx/hdmi_movie/hdmi_movie.runs/shift_ram_sobel_synth_1/shift_ram_sobel_sim_netlist.vhdl -of_objects [get_files E:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/shift_ram_sobel/shift_ram_sobel.xci]

add_files E:/wx/hdmi_movie/hdmi_movie.runs/shift_ram_sobel_synth_1/shift_ram_sobel.dcp -of_objects [get_files E:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/shift_ram_sobel/shift_ram_sobel.xci]

if {[file isdir E:/wx/hdmi_movie/hdmi_movie.ip_user_files/ip/shift_ram_sobel]} {
  catch { 
    file copy -force E:/wx/hdmi_movie/hdmi_movie.runs/shift_ram_sobel_synth_1/shift_ram_sobel_sim_netlist.v E:/wx/hdmi_movie/hdmi_movie.ip_user_files/ip/shift_ram_sobel
  }
}

if {[file isdir E:/wx/hdmi_movie/hdmi_movie.ip_user_files/ip/shift_ram_sobel]} {
  catch { 
    file copy -force E:/wx/hdmi_movie/hdmi_movie.runs/shift_ram_sobel_synth_1/shift_ram_sobel_sim_netlist.vhdl E:/wx/hdmi_movie/hdmi_movie.ip_user_files/ip/shift_ram_sobel
  }
}

if {[file isdir E:/wx/hdmi_movie/hdmi_movie.ip_user_files/ip/shift_ram_sobel]} {
  catch { 
    file copy -force E:/wx/hdmi_movie/hdmi_movie.runs/shift_ram_sobel_synth_1/shift_ram_sobel_stub.v E:/wx/hdmi_movie/hdmi_movie.ip_user_files/ip/shift_ram_sobel
  }
}

if {[file isdir E:/wx/hdmi_movie/hdmi_movie.ip_user_files/ip/shift_ram_sobel]} {
  catch { 
    file copy -force E:/wx/hdmi_movie/hdmi_movie.runs/shift_ram_sobel_synth_1/shift_ram_sobel_stub.vhdl E:/wx/hdmi_movie/hdmi_movie.ip_user_files/ip/shift_ram_sobel
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
