# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/Line_shift_ram_1bit/Line_shift_ram_1bit.xci
# IP: The module: 'Line_shift_ram_1bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/Line_shift_ram_1bit/Line_shift_ram_1bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Line_shift_ram_1bit'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/Line_shift_ram_1bit/Line_shift_ram_1bit.xci
# IP: The module: 'Line_shift_ram_1bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/Line_shift_ram_1bit/Line_shift_ram_1bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Line_shift_ram_1bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
