# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/fifo_64x1024_cnt/fifo_64x1024_cnt.xci
# IP: The module: 'fifo_64x1024_cnt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/fifo_64x1024_cnt/fifo_64x1024_cnt.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_64x1024_cnt'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/fifo_64x1024_cnt/fifo_64x1024_cnt_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_64x1024_cnt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/fifo_64x1024_cnt/fifo_64x1024_cnt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_64x1024_cnt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/fifo_64x1024_cnt/fifo_64x1024_cnt.xci
# IP: The module: 'fifo_64x1024_cnt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/fifo_64x1024_cnt/fifo_64x1024_cnt.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_64x1024_cnt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/fifo_64x1024_cnt/fifo_64x1024_cnt_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_64x1024_cnt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/fifo_64x1024_cnt/fifo_64x1024_cnt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_64x1024_cnt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
