# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}


start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param chipscope.maxJobs 4
  set_param simulator.modelsimInstallPath C:/modelsim2019.2/win64
  create_project -in_memory -part xc7a35tfgg484-2
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir D:/wx_prj/hdmi_movie_clean/hdmi_movie.cache/wt [current_project]
  set_property parent.project_path D:/wx_prj/hdmi_movie_clean/hdmi_movie.xpr [current_project]
  set_property ip_repo_paths D:/wx_prj/hdmi_movie_clean/axi_ip/axi_reg_1.0 [current_project]
  update_ip_catalog
  set_property ip_output_repo D:/wx_prj/hdmi_movie_clean/hdmi_movie.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  add_files -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.runs/synth_1/top.dcp
  set_msg_config -source 4 -id {BD 41-1661} -limit 0
  set_param project.isImplRun true
  add_files D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/mbs_bd.bd
  read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/clock_manage/clock_manage.xci
  read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/camrea_data_fifo/camrea_data_fifo.xci
  read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/fifo_64x1024_cnt/fifo_64x1024_cnt.xci
  read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/fifo_8xcol/fifo_8xcol.xci
  read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/shift_ram_sobel/shift_ram_sobel.xci
  read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/shift_reg_ram/shift_reg_ram.xci
  read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/vio_thresh/vio_thresh.xci
  read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/xdma_cmd_ram/xdma_cmd_ram.xci
  read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/mig_7series_axi/mig_7series_axi.xci
  read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/Line_shift_ram_1bit/Line_shift_ram_1bit.xci
  read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/fifo_delay/fifo_delay.xci
  read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/ram_buf/ram_buf.xci
  read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/vio_move/vio_move.xci
  set_param project.isImplRun false
  read_xdc D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/constrs_1/new/pin.xdc
  set_param project.isImplRun true
  link_design -top top -part xc7a35tfgg484-2
  set_param project.isImplRun false
  write_hwdef -force -file top.hwdef
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force top_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file top_drc_opted.rpt -pb top_drc_opted.pb -rpx top_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force top_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file top_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file top_utilization_placed.rpt -pb top_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file top_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step phys_opt_design
set ACTIVE_STEP phys_opt_design
set rc [catch {
  create_msg_db phys_opt_design.pb
  phys_opt_design 
  write_checkpoint -force top_physopt.dcp
  close_msg_db -file phys_opt_design.pb
} RESULT]
if {$rc} {
  step_failed phys_opt_design
  return -code error $RESULT
} else {
  end_step phys_opt_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force top_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file top_drc_routed.rpt -pb top_drc_routed.pb -rpx top_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file top_methodology_drc_routed.rpt -pb top_methodology_drc_routed.pb -rpx top_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file top_power_routed.rpt -pb top_power_summary_routed.pb -rpx top_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file top_route_status.rpt -pb top_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file top_timing_summary_routed.rpt -pb top_timing_summary_routed.pb -rpx top_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file top_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file top_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file top_bus_skew_routed.rpt -pb top_bus_skew_routed.pb -rpx top_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force top_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  catch { write_mem_info -force top.mmi }
  catch { write_bmm -force top_bd.bmm }
  write_bitstream -force top.bit 
  catch {write_debug_probes -quiet -force top}
  catch {file copy -force top.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

