set_property PACKAGE_PIN A19 [get_ports cmos1_scl]
set_property PACKAGE_PIN B15 [get_ports cmos1_sda]
set_property PACKAGE_PIN E17 [get_ports cmos1_reset]
set_property PACKAGE_PIN E19 [get_ports cmos1_pclk]
set_property PACKAGE_PIN E18 [get_ports cmos1_href]
set_property PACKAGE_PIN F18 [get_ports cmos1_vsync]
set_property PACKAGE_PIN B18 [get_ports {cmos1_d[7]}]
set_property PACKAGE_PIN B17 [get_ports {cmos1_d[6]}]
set_property PACKAGE_PIN C17 [get_ports {cmos1_d[5]}]
set_property PACKAGE_PIN A20 [get_ports {cmos1_d[4]}]
set_property PACKAGE_PIN A18 [get_ports {cmos1_d[3]}]
set_property PACKAGE_PIN C18 [get_ports {cmos1_d[2]}]
set_property PACKAGE_PIN C19 [get_ports {cmos1_d[1]}]
set_property PACKAGE_PIN D19 [get_ports {cmos1_d[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports cmos1_sda]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_scl]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_href]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_reset]

set_property PACKAGE_PIN Y18 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]

set_property PACKAGE_PIN F20 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property PACKAGE_PIN G15 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property PACKAGE_PIN G16 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]

set_property PACKAGE_PIN F19 [get_ports led0]
set_property PACKAGE_PIN E21 [get_ports led1]
set_property PACKAGE_PIN D20 [get_ports led2]
set_property PACKAGE_PIN C20 [get_ports led3]
set_property IOSTANDARD LVCMOS33 [get_ports led0]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property IOSTANDARD LVCMOS33 [get_ports led3]

set_property PACKAGE_PIN P17 [get_ports {hdmi_r[0]}]
set_property PACKAGE_PIN N17 [get_ports {hdmi_r[1]}]
set_property PACKAGE_PIN R19 [get_ports {hdmi_r[2]}]
set_property PACKAGE_PIN P19 [get_ports {hdmi_r[3]}]
set_property PACKAGE_PIN T18 [get_ports {hdmi_r[4]}]
set_property PACKAGE_PIN R18 [get_ports {hdmi_r[5]}]
set_property PACKAGE_PIN U21 [get_ports {hdmi_r[6]}]
set_property PACKAGE_PIN T21 [get_ports {hdmi_r[7]}]
set_property PACKAGE_PIN V22 [get_ports {hdmi_g[0]}]
set_property PACKAGE_PIN U22 [get_ports {hdmi_g[1]}]
set_property PACKAGE_PIN V20 [get_ports {hdmi_g[2]}]
set_property PACKAGE_PIN U20 [get_ports {hdmi_g[3]}]
set_property PACKAGE_PIN W22 [get_ports {hdmi_g[4]}]
set_property PACKAGE_PIN W21 [get_ports {hdmi_g[5]}]
set_property PACKAGE_PIN Y22 [get_ports {hdmi_g[6]}]
set_property PACKAGE_PIN Y21 [get_ports {hdmi_g[7]}]
set_property PACKAGE_PIN AA21 [get_ports {hdmi_b[0]}]
set_property PACKAGE_PIN AA20 [get_ports {hdmi_b[1]}]
set_property PACKAGE_PIN AB22 [get_ports {hdmi_b[2]}]
set_property PACKAGE_PIN AB21 [get_ports {hdmi_b[3]}]
set_property PACKAGE_PIN AB20 [get_ports {hdmi_b[4]}]
set_property PACKAGE_PIN AA19 [get_ports {hdmi_b[5]}]
set_property PACKAGE_PIN W20 [get_ports {hdmi_b[6]}]
set_property PACKAGE_PIN W19 [get_ports {hdmi_b[7]}]
set_property PACKAGE_PIN AB18 [get_ports hdmi_clk]
set_property PACKAGE_PIN AA18 [get_ports hdmi_hsync]
set_property PACKAGE_PIN V19 [get_ports hdmi_vsync]
set_property PACKAGE_PIN V18 [get_ports hdmi_dvalid]

set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_r[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_r[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_r[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_r[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_g[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_b[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_b[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_b[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_dvalid]

create_clock -period 20.000 -name sys_clk [get_ports clk_in]
create_clock -period 12.000 -name camera_clk [get_ports cmos1_pclk]

create_clock -period 5.000 -name ddr_ref_clk [get_pins clock_manage_inst/inst/mmcm_adv_inst/CLKOUT0]
create_clock -period 10.000 -name sys_clk_100 [get_pins clock_manage_inst/inst/mmcm_adv_inst/CLKOUT1]
create_clock -period 20.000 -name sys_clk_50 [get_pins clock_manage_inst/inst/mmcm_adv_inst/CLKOUT2]
create_clock -period 100.000 -name sys_clk_9 [get_pins clock_manage_inst/inst/mmcm_adv_inst/CLKOUT3]

create_clock -period 10.000 -name ddr_clk [get_pins ddr3_top_inst/u_mig_7series_axi_inst/u_mig_7series_axi_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]

set_false_path -from [get_clocks camera_clk] -to [get_clocks ddr_clk]
set_false_path -from [get_clocks ddr_clk] -to [get_clocks camera_clk]

set_false_path -from [get_clocks ddr_clk] -to [get_clocks sys_clk_25]
set_false_path -from [get_clocks sys_clk_25] -to [get_clocks ddr_clk]

set_false_path -from [get_clocks ddr_clk] -to [get_clocks ddr_ref_clk]
set_false_path -from [get_clocks ddr_ref_clk] -to [get_clocks ddr_clk]

set_false_path -from [get_clocks ddr_clk] -to [get_clocks sys_clk_9]
set_false_path -from [get_clocks sys_clk_9] -to [get_clocks ddr_clk]

set_false_path -from [get_clocks camera_clk] -to [get_clocks sys_clk_100]
set_false_path -from [get_clocks sys_clk_100] -to [get_clocks camera_clk]



set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets hdmi_clk_OBUF]
