# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_dlmb_bram_if_cntlr_1/mbs_bd_dlmb_bram_if_cntlr_1.xci
# IP: The module: 'mbs_bd_dlmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_dlmb_bram_if_cntlr_1/mbs_bd_dlmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbs_bd_dlmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_dlmb_bram_if_cntlr_1/mbs_bd_dlmb_bram_if_cntlr_1.xci
# IP: The module: 'mbs_bd_dlmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_dlmb_bram_if_cntlr_1/mbs_bd_dlmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbs_bd_dlmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
