# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/fifo_8xcol/fifo_8xcol.xci
# IP: The module: 'fifo_8xcol' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/fifo_8xcol/fifo_8xcol.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8xcol'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/fifo_8xcol/fifo_8xcol_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8xcol'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/fifo_8xcol/fifo_8xcol.xci
# IP: The module: 'fifo_8xcol' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/fifo_8xcol/fifo_8xcol.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8xcol'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/fifo_8xcol/fifo_8xcol_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8xcol'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
