# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/clock_manage/clock_manage.xci
# IP: The module: 'clock_manage' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/clock_manage/clock_manage_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_manage'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/clock_manage/clock_manage.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_manage'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/clock_manage/clock_manage_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_manage'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/clock_manage/clock_manage.xci
# IP: The module: 'clock_manage' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/clock_manage/clock_manage_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_manage'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/clock_manage/clock_manage.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_manage'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/clock_manage/clock_manage_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_manage'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
