# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# Block Designs: bd/mbs_bd/mbs_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbs_bd || ORIG_REF_NAME==mbs_bd} -quiet] -quiet

# IP: bd/mbs_bd/ip/mbs_bd_microblaze_0_0/mbs_bd_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbs_bd_microblaze_0_0 || ORIG_REF_NAME==mbs_bd_microblaze_0_0} -quiet] -quiet

# IP: bd/mbs_bd/ip/mbs_bd_rst_Clk_100M_0/mbs_bd_rst_Clk_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbs_bd_rst_Clk_100M_0 || ORIG_REF_NAME==mbs_bd_rst_Clk_100M_0} -quiet] -quiet

# IP: bd/mbs_bd/ip/mbs_bd_axi_uartlite_0_0/mbs_bd_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbs_bd_axi_uartlite_0_0 || ORIG_REF_NAME==mbs_bd_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mbs_bd/ip/mbs_bd_microblaze_0_axi_periph_0/mbs_bd_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbs_bd_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mbs_bd_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mbs_bd/ip/mbs_bd_axi_reg_0_0/mbs_bd_axi_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbs_bd_axi_reg_0_0 || ORIG_REF_NAME==mbs_bd_axi_reg_0_0} -quiet] -quiet

# IP: bd/mbs_bd/ip/mbs_bd_xbar_0/mbs_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbs_bd_xbar_0 || ORIG_REF_NAME==mbs_bd_xbar_0} -quiet] -quiet

# IP: bd/mbs_bd/ip/mbs_bd_dlmb_v10_1/mbs_bd_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbs_bd_dlmb_v10_1 || ORIG_REF_NAME==mbs_bd_dlmb_v10_1} -quiet] -quiet

# IP: bd/mbs_bd/ip/mbs_bd_ilmb_v10_1/mbs_bd_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbs_bd_ilmb_v10_1 || ORIG_REF_NAME==mbs_bd_ilmb_v10_1} -quiet] -quiet

# IP: bd/mbs_bd/ip/mbs_bd_dlmb_bram_if_cntlr_1/mbs_bd_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbs_bd_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==mbs_bd_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mbs_bd/ip/mbs_bd_ilmb_bram_if_cntlr_1/mbs_bd_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbs_bd_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mbs_bd_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mbs_bd/ip/mbs_bd_lmb_bram_1/mbs_bd_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbs_bd_lmb_bram_1 || ORIG_REF_NAME==mbs_bd_lmb_bram_1} -quiet] -quiet

# IP: bd/mbs_bd/ip/mbs_bd_mdm_1_1/mbs_bd_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mbs_bd_mdm_1_1 || ORIG_REF_NAME==mbs_bd_mdm_1_1} -quiet] -quiet

# XDC: bd/mbs_bd/mbs_bd_ooc.xdc
