# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath C:/modelsim2019.2/win64
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/wx_prj/hdmi_movie_clean/hdmi_movie.cache/wt [current_project]
set_property parent.project_path D:/wx_prj/hdmi_movie_clean/hdmi_movie.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/wx_prj/hdmi_movie_clean/axi_ip/axi_reg_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo d:/wx_prj/hdmi_movie_clean/hdmi_movie.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/move_detect/VIP_Bit_Erosion_Detector.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/move_detect/VIP_Matrix_Generate_3X3_1Bit.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/move_detect/VIP_RGB888_YCbCr444.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/move_detect/Video_Image_Processor.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/axi_master_rd.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/axi_master_wr.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/cmd_ctrl.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/data_ctrl.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/move_detect/data_d.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/ddr3_top.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/move_detect/frame_difference.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/frame_speed.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/matrix_add.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/mean_filter.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/move_detect/move_detect.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/ov5640_cfg.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/ov5640_data.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/ov5640_iic.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/move_detect/position.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/power_on_delay.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/rgbtogray.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/shift_register_2taps.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/sig_delay.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/sig_pdg.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/signal_sys.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/sobel_ctrl.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/uart_data_gen.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/vga_ctrl.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/wr_time_ctrl.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/xdma_v1.v
  D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/new/top.v
}
add_files D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/mbs_bd.bd
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_microblaze_0_0/mbs_bd_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_microblaze_0_0/mbs_bd_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_microblaze_0_0/mbs_bd_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_rst_Clk_100M_0/mbs_bd_rst_Clk_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_rst_Clk_100M_0/mbs_bd_rst_Clk_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_rst_Clk_100M_0/mbs_bd_rst_Clk_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_axi_uartlite_0_0/mbs_bd_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_axi_uartlite_0_0/mbs_bd_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_axi_uartlite_0_0/mbs_bd_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_xbar_0/mbs_bd_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_dlmb_v10_1/mbs_bd_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_dlmb_v10_1/mbs_bd_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_ilmb_v10_1/mbs_bd_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_ilmb_v10_1/mbs_bd_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_dlmb_bram_if_cntlr_1/mbs_bd_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_ilmb_bram_if_cntlr_1/mbs_bd_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_lmb_bram_1/mbs_bd_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_mdm_1_1/mbs_bd_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_mdm_1_1/mbs_bd_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/mbs_bd_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/bd/mbs_bd/ip/mbs_bd_microblaze_0_0/data/mb_bootloop_le.elf]

read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/clock_manage/clock_manage.xci
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/clock_manage/clock_manage_board.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/clock_manage/clock_manage.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/clock_manage/clock_manage_ooc.xdc]

read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/camrea_data_fifo/camrea_data_fifo.xci
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/camrea_data_fifo/camrea_data_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/camrea_data_fifo/camrea_data_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/camrea_data_fifo/camrea_data_fifo_ooc.xdc]

read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/fifo_64x1024_cnt/fifo_64x1024_cnt.xci
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/fifo_64x1024_cnt/fifo_64x1024_cnt.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/fifo_64x1024_cnt/fifo_64x1024_cnt_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/fifo_64x1024_cnt/fifo_64x1024_cnt_ooc.xdc]

read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/fifo_8xcol/fifo_8xcol.xci
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/fifo_8xcol/fifo_8xcol.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/fifo_8xcol/fifo_8xcol_ooc.xdc]

read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/shift_ram_sobel/shift_ram_sobel.xci
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/shift_ram_sobel/shift_ram_sobel_ooc.xdc]

read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/shift_reg_ram/shift_reg_ram.xci
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/shift_reg_ram/shift_reg_ram_ooc.xdc]

read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/vio_thresh/vio_thresh.xci
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/vio_thresh/vio_thresh.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/vio_thresh/vio_thresh_ooc.xdc]

read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/xdma_cmd_ram/xdma_cmd_ram.xci
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/xdma_cmd_ram/xdma_cmd_ram_ooc.xdc]

read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/mig_7series_axi/mig_7series_axi.xci
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/mig_7series_axi/mig_7series_axi/user_design/constraints/mig_7series_axi.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/mig_7series_axi/mig_7series_axi/user_design/constraints/mig_7series_axi_ooc.xdc]

read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/Line_shift_ram_1bit/Line_shift_ram_1bit.xci
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/Line_shift_ram_1bit/Line_shift_ram_1bit_ooc.xdc]

read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/fifo_delay/fifo_delay.xci
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/fifo_delay/fifo_delay.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/fifo_delay/fifo_delay_ooc.xdc]

read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/ram_buf/ram_buf.xci
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/ram_buf/ram_buf_ooc.xdc]

read_ip -quiet D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/vio_move/vio_move.xci
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/vio_move/vio_move.xdc]
set_property used_in_implementation false [get_files -all d:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/sources_1/ip/vio_move/vio_move_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files D:/wx_prj/hdmi_movie_clean/hdmi_movie.srcs/constrs_1/new/pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
