# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/camrea_data_fifo/camrea_data_fifo.xci
# IP: The module: 'camrea_data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/camrea_data_fifo/camrea_data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'camrea_data_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/camrea_data_fifo/camrea_data_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'camrea_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/camrea_data_fifo/camrea_data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'camrea_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/camrea_data_fifo/camrea_data_fifo.xci
# IP: The module: 'camrea_data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/camrea_data_fifo/camrea_data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'camrea_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/camrea_data_fifo/camrea_data_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'camrea_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_prj/wx/hdmi_movie/hdmi_movie.srcs/sources_1/ip/camrea_data_fifo/camrea_data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'camrea_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
